"""Add table Constraints

Revision ID: e81e85f3ed72
Revises: 375af41309c4
Create Date: 2026-07-27 15:39:42.216124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81e85f3ed72'
down_revision = '375af41309c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_exercise_name", ['name'])

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_workout_exerciise', ['workout_id', 'exercise_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_constraint('unique_workout_exerciise', type_='unique')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
